config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root 'posts#index'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  before_create :set_comment_number

  #this is because we didn't add to the model the 'body' or 'content' of the comment
  has_rich_text :body

  #Polymorphic comments
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  def set_comment_number
    self.comment_number = user.comment_created  
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  #comments 
  has_many :comments, as: :commentable, dependent: :destroy

  #Active storage from rails 5
  has_one_attached :image
  has_one_attached :photo
  #has_many_attached :... --> por si quiero varias imagenes, en este caso solo quiero dos 

  #Action text from rails 6
  has_rich_text :body

  #Validations on this body:
  validates :title, length: {minimum: 5}
  validates :body, length: {minimum: 25}

  #pagination
  self.per_page = 10
  
  #friendly_id
  extend FriendlyId
  friendly_id :title, use: :slugged  

  #for the size of the img(i can do with css but also in this way)
  def optimize_image(image, x, y)
    return image.variant(resize_to_fill: [x,y]).processed  
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_one_attached :avatar

    #gaby@example.com -> self.email.split('@') -> ['gaby', 'example.com'] -> [0] -> 'gaby'.capitalize -> Gaby  
  def username 
    return email.split("@")[0].capitalize
  end

  def comment_created
    #this is the same thing as: num_comments += 1
    self.number_of_comments = number_of_comments + 1
    save
    number_of_comments #If I want, I can write 'return' 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_admin!

  private 

  def is_admin!
    if current_user && current_user.admin
    else
      redirect_to root_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable, only: [:create] #it's for the method find_commentable
  before_action :set_comment, except: [:create] #we only use the commentable inside of the create action, so for the other ones we wanna use set_comments, 
  before_action :authenticate_user!

  def create
    #commentable it's the parent so we make sons for this 
    @comment = @commentable.comments.build(comment_params)
    @comment.user = current_user
    if params[:comment_id]
      @comment.reply = true
    end
    @comment.save
  end

  def edit 
  end

  def update 
    if @comment.edit_history == ''
      #\n => replace \n with <br /><hr />
      @comment.edit_history = "Original:" + @content.body.body.to_plain_text + "\n"
    else 
      @comment.edit_history = @comment.edit_history + "Edit: " + params[:comment][:body] + "\n"
    end
    @comment.update(comment_params)
  end

  def destroy
    @comment.destroy
  end

  def history
  end

  private 

  def comment_params 
    params.require(:comment).permit(:body)
  end

  def find_commentable
    #comment --> if the parent it's comment 
    if params[:comment_id]
      @commentable = Comment.find_by_id(params[:comment_id])
    elsif params[:post_id] 
      #post --> if it's a post 
      #we use Post.friendly_id because we put in the posts_controller that
      @commentable = Post.friendly.find(params[:post_id])

    end
  end

  def set_comment
    @coment = Coment.find(params[:id])
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  #To be sure that the user is log in
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_admin!,  except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page])
  end

  # GET /posts/1 or /posts/1.json
  def show
    views = @post.views + 1
    @post.update(views: views)
    @comments = @post.comments.order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="comment-container" id="comment-<%= comment.id %>%">
  <div class="container">
    <%= render 'comments/comments', comment: comment, local: Comment.new%>

    <% unless comment.reply %>
      <div class="row">
        <div class="col-4">
        </div>
        <div class="col-8">
          <div class="comment-form-nested">
            <%= render 'comments/form', commentable: comment, local: Comment.new %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_comments.html.erb
<div class="row">
  <div class="col-3">
    <div class="row">
      <% if comment.user.avatar.attached? %>
      <%= image_tag(comment.user.avatar, class:'comment-avatar') %>
      <% else %>
            <%= image_tag('/default_profile.png', class:'comment-avatar') %>
      <% end %>
    </div>
    <div class="row">
      <div class="comment-timestamp" id="edit-history-text-<%= comment.id %>">
        <% render 'comments/edit_history_text', comment: comment %>
      </div>
    </div>
  </div>

  <div class="col-9">
    <div class="row">
      <div class="col-8">
        <div class="comment-username">
          <%= comment.user.username %>
        </div>
          <div class="comment-number">
            #<%= comment.comment_number %>
          </div>
      </div>

      <% if current_user && () %>
    </div>
  </div>
</div>

<!--Modal of edit_history_text-->

<div class="modal fade" id="edit_history" tabindex="-1" role="dialog" aria-labelleddy=":Comment Edit History" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        
        <h5 class="modal-title" id="edit_history_title"><%= comment.user.username %>'s Edit History</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="edit_history-body">
        <%= render 'comments/edit_history', comment: comment %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/comments/_edit_history.html.erb
<%= comment.edit_history.gsub(/\n/, '<br/><hr/>').html_safe %>

app/views/comments/_edit_history_text.html.erb
<%= time_ago_in_words(comment.created_at) %> ago
<br />
<% edit_history = comment.edit_history == "" ? "" : "Last edited" + time_ago_in_words(comment.updated_at) + "ago" %>


<%= link_to(edit_history, 'javascript:;', data: {toggle: "modal", target: "#edit_history"})%>

if (user.age >= 21) {
  can drink = true
} else {
  can drink = false 
}

bool can_drink = user.age >= 21? true : false

app/views/comments/_form.html.erb
<div class="row">
  <div class="comment-form">
  <!--it's different than form_for-> i'ts use if I want to redirect to a new page-->
    <%= form_with model: [commentable, local] do |f| %>
    <div class="form-group">
      <%= f.rich_text_area :body, placeholder: "Say something...", class:"reply-form-#{commentable.id}", id: f.object_id, method: :patch %>
      <%= f.submit "Post", class:'btn btn-dark float-right' %>
    </div>
    <% end %>
  </div>
</div>

<script>
  $(document).on("turbolinks:load", function(){
    $(".trix-button-group--file-tools").remove();
    document.addEventListener("trix-file-accept", function(event){
      event.preventDefault();
    });
  });
</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href=" <%= root_path %> ">BLOG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href=" <%= about_path %> ">About</a>
      </li>
    </ul>
    <!--class="mr-auto" me deja las cosas como centradas-->
    <ul class="navbar-nav ml-auto">
    <% if current_user %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= current_user.username %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <% if current_user.admin %>
          <a class="dropdown-item" href="#">New Post</a>
          <% end %>
          <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account Settings</a>
          <div class="dropdown-divider"></div>
          <%= link_to 'Log out', destroy_user_session_path, class:"dropdown-item", method: :delete %>
        </div>
      </li>
      <% else %>
        <li class="nav-item">
        <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
        </li>
      <li class="nav-item">
        <%= link_to 'Sign in', new_user_session_path, class:"nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogEpisode1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4">About Me</h1>
    <div class="row">
      <p class="text-align: justify">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to  <br><br>
        make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        <br>
      </p>
    <hr class="my-4">
    </div>
    <div class="btn-group" role="group" aria-label="Basic example">
      <button type="button" class="btn btn-secondary"><%= link_to 'Github', 'https://github.com/Gabriela-oss' %></button>
      <button type="button" class="btn btn-secondary"><%= link_to 'Linkedin', 'https://www.linkedin.com/in/gabrielasol%C3%ADschavarr%C3%ADa/' %></button>
      <button type="button" class="btn btn-secondary"><%= link_to 'Facebook', 'https://empieza.desafiolatam.com/users/gabriela-sols-chavarra/complete_profile' %></button>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>

  <div class="form-inputs">
    <%= f.text_field :title, class:'form-control string' %>
    <%= f.label :image, class:'form-control' %>
    <%= f.file_field :image %>
    <%= f.label :photo, class:'form-control' %>
    <%= f.file_field :photo %>
    <%= f.rich_text_area :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="digg_pagination">
      <%= will_paginate @post, :container => false %>
    </div>
  </div>
  <% @posts.each do |post| %>
    <div class="row"> 
      <div class="card mb-3">
        <img class="card-img-top"
        src="<% url_for post.optimize_image(post.image, 506, 180)%>"
        alt="Blog Post Image Card"
        />
        <div class="card_body">
          <h5 class="card-title">
            <%= link_to post.title, post %>
          </h5>
          <p class="card-text"><%= post.body.to_plain_text.truncate_words(50) %></p>
          <p class="card-text">
            <small class="text-muted">
              <%= post.updated_at.strftime("%A, %B %e, %Y") %> by
              <%= post.user.username %> | <%= pluralize(post.views, "View") %> | comments 0
            </small>
          </p>
        </div>
      </div>
    </div>
          binding.pry
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div style="width:100%; height:300px; overflow-y:hidden">
  <%= image_tag(@post.photo, style:'width:100%') %>
</div>
<div class="container" style="margin-top: 2em">
  <div class="row">
    <div class="image" style="width:100%">
      <h1 class="display-4">
        <%= link_to @post.title, root_path %>
      </h1>
      <p class="lead">
        <%= @post.updated_at.strftime("%A, %B %e, %Y") %> by <%= @post.user.username %> | <%= pluralize(@post.views, "View") %>
      </p>
      <hr class="my-4"/>
      <div class="post_body">
        <%= @post.body %>
      </div>
    </div>
  </div>
</div>

<div class="container">
<!--we need to give it the parent of the thing we are creating(the parent it's the post), also this is the way to create something called local, this has a new comment in it, so when we do the form builder we can do that -->
  <%= render 'comments/form', commentable: @post, local: Comment.new %> 

  <div id="comment-pane">
    <% @comment.each do |comment| %>
    <% render comment %>
    <% end %>
  </div>
</div>